### ISSUE TITLE
`sql_to_df` error "Could not locate column in row for column 'ndim'"

### ISSUE THREAD

**Issue by multidis** [rosspalmer/bitQuant#1]
Python 2.7.3

```
import bitquant as bq
bq.trades_df()
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bitquant/sql.py", line 135, in trades_df
    symbol=symbol, start=start, end=end)
  File "bitquant/sql.py", line 96, in sql_to_df
    df = DataFrame(result, columns=headers)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 240, in **init**
    if is_list_like(data[0]) and getattr(data[0], 'ndim', 1) == 1:
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2654, in _key_fallback
    expression._string_or_unprintable(key))
sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'ndim'"

Notes:
- sqlite configured and contains `trades`-table data as seen in db content browser;
- initial debugging of the error-causing `DataFrame(result, columns=headers)` statement suggests `getattr` in pandas still raises an exception even though a default was provided for `ndim`, possibly something similar to [this](http://stackoverflow.com/questions/24794696/why-is-getattr-throwing-an-exception-when-an-attribute-doesnt-exist) case.

**Comment by multidis** [comment]
Must be a `pandas`-issue: no errors when using 0.15.2 instead of 0.13.1. This can probably be closed.

**Comment by rosspalmer** [comment]
excellent, i had never gotten an error like that before and it did not look fun :) let me know if we need to reopen.
