### ISSUE TITLE
Coinbase returns no timestamps in v0.3.* API

### ISSUE THREAD

**Issue by multidis** [rosspalmer/bitQuant#18]
When running the following:

```
import bitquant as bq
symb = 'btcusd'
data_tr = bq.data()
exch = 'coinbase'
data_tr.add_trades(exch, symb, limit=100, since='', auto_since='no', ping_limit=1.0)
data_tr.run_trades(exch, symb)
print data_tr.trd
```

`data_tr.trd` does not contain `timestamp`-column. This seems to happen with coinbase only (at least among a few exchanges I tested no others behaved like that).

**Comment by rosspalmer** [comment]
Thank you for pointing this out, I mistakenly had a 'symbol' when I needed an 'exchange'. I fixed this issue in this [commit](https://github.com/rosspalmer/bitQuant/commit/844ea5a846f4aec6e896d2b09ee9f619883168c1)
