### ISSUE TITLE
OHLCV values at the closing end of each timestep

### ISSUE THREAD

**Issue by multidis** [rosspalmer/bitQuant#6]
Currently, as the `trades_to_price` function produces OHLCV dataframe, each timestep/bin/interval values are assigned in the beginning of it. This seems to be at odds with a convention that the closing time point contains trade volume over the latest bin (i.e., close price and volume reflect what happened during the timestep).

This can be fixed with additional options provided to Pandas' [resample](http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.resample.html) function. Submitting a pull request for the fix.

**Comment by rosspalmer** [comment]
[Commited](https://github.com/rosspalmer/bitQuant/commit/bbe6293ae87b81e389c8ee813f7a4ab395777aad)
