### ISSUE TITLE
handling exchange communication errors

### ISSUE THREAD

**Issue by multidis** [rosspalmer/bitQuant#8]
When a cron class is running and there is a problem with exchange communication, an exception is being raised which crashes the cron-run session. This is a problem if e.g. one wants to query several exchanges frequently and all subsequent runs within cron limit time end up being aborted.

Pull request for doing exception catching at [server.py L79](https://github.com/rosspalmer/bitQuant/blob/master/bitquant/server.py#L79)

```
    try:
            trd = ping.to_sql()
    except:
            pass
```

**Comment by rosspalmer** [comment]
[Fixed](https://github.com/rosspalmer/bitQuant/commit/0816f3fd68a198da4caeb59b10426f587f1212fa)

**Comment by multidis** [comment]
For a constantly running process of adding latest trades to the database, does this seem to be a reasonable approach:

```
while True
    {ping exchange 1}
    {try-catch add ping to db}
    { same for exchange 2, etc. }
```

Any downsides for doing this? Would memory use keep growing after endless reallocation of dataframes in python?

**Comment by rosspalmer** [comment]
No actually, while loops can get out of control but I experimented a bit and looks like resources stay fairly constant.

I started working on a redesign and its a lot smaller. It'll have a `ratio` variable for each exchange so that low volume exchanges aren't pinged at the same rate as high volume.

**Comment by multidis** [comment]
Exchange-specific ping timing is an interesting idea. What probably matters the most in that context is the number of trades per unit time (which, just like the trade volume, is a rapidly changing metric; order arrival models provide some hints). Perhaps the ratio

```
{number of new transactions received in a query} / {total number of transactions queried}
```

could be used as a feedback loop parameter to adjust ping frequency of an exchange such that the ratio stays near a chosen default value, say, 0.5.

**Comment by rosspalmer** [comment]
Definitely what I was thinking, I'm a little bit busy the rest of the week but should be able to send out an update this weekend.

**Comment by rosspalmer** [comment]
Revised the `cron` class to use the while loop discussed above with a ratio function. Here's the [commit](https://github.com/rosspalmer/bitQuant/commit/c92bff121d043fcbd6ed4123b7ad84dc6b196405).

I go into more detail on the new class in the [data maintenance tutorial](https://github.com/rosspalmer/bitQuant/wiki/Tutorial:-API-Data-Maintenance).

**Comment by multidis** [comment]
This was a helpful step forward in data maintenance. Filed a related issue https://github.com/rosspalmer/bitQuant/issues/11 separately.
