### ISSUE TITLE
Removing incomplete ends of price data

### ISSUE THREAD

**Issue by multidis** [rosspalmer/bitQuant#9]
`tools.py` line

```
prc = prc[1:-1]
```

which was commented-out in 7cc92480d1007c09380cce6d0032c77c1632a5dc actually helps remove incomplete OHLC timesteps.

**Comment by rosspalmer** [comment]
Fixed in this [commit](https://github.com/rosspalmer/bitQuant/commit/c92bff121d043fcbd6ed4123b7ad84dc6b196405).
